Define carla host and port
carla-simulator/traffic-generation-editor pull request #1
Opened 2021-04-19 17:13 UTC by lrstttl

By default, the plugin tries to connect to CARLA running on localhost, port 2000 and there is no option to input other values.

I added an additional dialog window to input host and port other than the default values. The dialog is opened after clicking the plugin's "Connect to carla" button.

![image](https://user-images.githubusercontent.com/28296759/115276297-26c11180-a143-11eb-94b9-7119e11e61ab.png)

2021-04-20 07:12 UTC, fabianoboril requested changes

2021-04-20 07:12 UTC, fabianoboril commented on carla_connect/mapupdate.py
> +            self.carla_client = carla.Client(self.host, self.port)
Can we provide host/port via constructor parameters?

2021-04-20 07:12 UTC, fabianoboril commented on carla_scenario_editor.py
> +        MapUpdate.port = self.port
Please provide host/port as MapUpdate constructor parameters

2021-04-20 07:12 UTC, fabianoboril commented on carla_connect/mapupdate.py
> +            self.carla_client = carla.Client(self.host, self.port)
What happens, if host is not a string, but an IP? Is this properly interpreted by the GUI?

2021-04-20 13:20 UTC, lrstttl commented on carla_connect/mapupdate.py
> +            self.carla_client = carla.Client(self.host, self.port)
The input from the dialog GUI always is a string, and it works with hostnames and IPs as carla.Client() expects a string.

2021-04-20 13:28 UTC, lrstttl commented on carla_connect/mapupdate.py
> +            self.carla_client = carla.Client(self.host, self.port)
This will introduce some more changes, as `MapUpdate` is instantiated multiple times, e.g. in `carla_connect/addcam.py`, classes `Spawn`, `ImageProcessor` or `carla_connect/carla_connect_dockwidget.py`, class `CarlaConnectDockWidget`. So all of these classes need to be provided with host/port in their constructors

2021-04-20 13:49 UTC, fabianoboril commented on carla_connect/mapupdate.py
> +            self.carla_client = carla.Client(self.host, self.port)
We can use default values in the constructor to overcome this.

2021-04-20 13:50 UTC, fabianoboril commented on carla_connect/mapupdate.py
> +            self.carla_client = carla.Client(self.host, self.port)
Great

2021-04-23 12:42 UTC, lrstttl commented
Host and port are now provided by constructor arguments.

2021-04-23 12:44 UTC, lrstttl commented on carla_connect/mapupdate.py
> +            self.carla_client = carla.Client(self.host, self.port)
Done

2021-04-23 12:44 UTC, lrstttl commented on carla_scenario_editor.py
> +        MapUpdate.port = self.port
Done

2021-04-26 09:26 UTC, fabianoboril approved these changes

2021-05-05 13:34 UTC, merged